[package]
name = "north"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.3"
rand = "0.8"